Clair chart changes for security integration
devtron-labs/charts pull request #122
Opened 2022-09-13 05:30 UTC by dheeth

- Default values as well as config changes

2022-09-14 11:05 UTC, nishant-d requested changes

2022-09-14 11:05 UTC, nishant-d commented on charts/clair/templates/deployment.yaml
> +          "until pg_isready -h {{ .Values.config.postgresHost }} -p 5432;
user `Values.config.postgresPort`

2022-09-14 11:05 UTC, nishant-d commented on charts/clair/values.yaml
> +    memory: 3Gi
no request?

2022-09-22 03:39 UTC, dheeth commented on charts/clair/templates/deployment.yaml
> +          "until pg_isready -h {{ .Values.config.postgresHost }} -p 5432;
Done

2022-09-22 03:39 UTC, dheeth commented on charts/clair/values.yaml
> +    memory: 3Gi
Added requests

2022-09-24 12:17 UTC, prakarsh-dt approved these changes

2022-09-24 12:22 UTC, prakarsh-dt approved these changes

2022-09-24 12:22 UTC, merged