feat: Add k8s-chart
devtron-labs/charts pull request #257
Opened 2024-12-10 10:43 UTC by Neha130

2024-12-26 09:15 UTC, prakarsh-dt commented on charts/k8s-shield/values.yaml
> +pvcCreationPolicy:
```yaml
defaultPolicies:
  create: true
  policies:
    pvcCreationPolicy: true
    namespaceDeletionPolicy: true
    loadBalancerCreationPolicy: true
    
    
policyDefinitions:
  namespaceDeletionPolicy:
    enabled: false  # If true, this policy restricts the deletion of namespaces.
    namespaces:     # List of namespaces that you want to protect from deletion
      - kube-system
    validationActions:  
      - Deny
  loadBalancerCreationPolicy:
    enabled: false  # If true, the policy blocks creation of LoadBalancer type services.
    namespaces: {}     # List of namespaces where the policy applies.
    validationActions:  
      - Deny
  ```

2024-12-26 09:18 UTC, prakarsh-dt requested changes

2024-12-26 09:18 UTC, prakarsh-dt commented on charts/k8s-shield/values.yaml
Use the following standard format like kubeprometheus stack
```yaml
defaultPolicies:
  create: true
  policies:
    pvcCreationPolicy: true
    namespaceDeletionPolicy: true
    loadBalancerCreationPolicy: true
    
    
policyDefinitions:
  namespaceDeletionPolicy:
    enabled: false  # If true, this policy restricts the deletion of namespaces.
    namespaces:     # List of namespaces that you want to protect from deletion
      - kube-system
    validationActions:  
      - Deny
  loadBalancerCreationPolicy:
    enabled: false  # If true, the policy blocks creation of LoadBalancer type services.
    namespaces: {}     # List of namespaces where the policy applies.
    validationActions:  
      - Deny
```

2024-12-31 09:59 UTC, pawan-59 approved these changes

2024-12-31 10:10 UTC, Neha130 commented on charts/k8s-shield/values.yaml
Updated the values.yaml accordingly

2025-01-08 12:30 UTC, pawan-59 submitted a review, later dismissed

2025-01-14 10:46 UTC, prakarsh-dt approved these changes

2025-01-14 10:52 UTC, pawan-59 approved these changes

2025-01-14 10:53 UTC, merged